<div>
				<ul class="breadcrumb">
					<li>
						<a href="#">Anasayfa</a> <span class="divider">/</span>
					</li>
					<li>
						<a href="#">Ödevler</a>
					</li>
                                </ul>
				
</div>
    <div class="row-fluid sortable">		
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-user"></i>Ödevler</h2>
                            <div class="box-icon">
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                    <div class="box-content">
                            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                              <thead>
                                      <tr>
                                              <th>Bölüm</th>
                                              <th>Ders</th>
                                              <th>Başlık</th>
                                              <th>Bitiş Zamanı</th>
                                              <th></th>
                                      </tr>
                              </thead>   
                              <tbody>
                                  <?php if(count($this->homeworks)){
                                    foreach ($this->homeworks as $homework) {
                                        $departmentModel = new Application_Model_DbTable_Department();
                                        $classModel = new Application_Model_DbTable_Class();
                                        $lessonModel = new Application_Model_DbTable_Lesson();
                                        
                                  ?>
                                    <tr>
                                        <td class="center"><?php echo $departmentModel->getByFilter(array('id' => $homework['department_id']))->name?></td>
                                        <td class="center"><?php echo $lessonModel->getByFilter(array('id' => $homework['lesson_id']))->name; ?></td>
                                            <td class="center"><?php echo substr($homework['title'], 0, 60)?></td>
                                            <td class="center"><?php echo $homework['finish_time']?></td>
                                            <td class="center">
                                                    <a class="btn btn-success" href="<?php echo $this->baseUrl('/teacher/homework/show/'.$homework['id']);?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Görüntüle                                            
                                                    </a>
                                                    <a class="btn btn-info" href="<?php echo $this->baseUrl('/teacher/homework/edit/'.$homework['id']);?>">
                                                            <i class="icon-edit icon-white"></i>  
                                                            Düzenle                                            
                                                    </a>
                                                    <a class="btn btn-danger" href="#">
                                                            <i class="icon-trash icon-white"></i> 
                                                            Sil
                                                    </a>
                                                    <a class="btn btn-danger" href="<?php echo $this->baseUrl('/teacher/homework/pdf-download/'.$homework['id']);?>">
                                                            <i class="icon-trash icon-white"></i> 
                                                            Pdf Olarak İndir
                                                    </a>
                                            </td>
                                    </tr>
                                  <?php  }};?>
                              </tbody>
                      </table>            
                    </div>
            </div><!--/span-->

    </div><!--/row-->
