<div>
				<ul class="breadcrumb">
					<li>
						<a href="#">Anasayfa</a> <span class="divider">/</span>
					</li>
					<li>
                                            <a href="#">Dersin Ödevleri</a><span class="divider">/</span>
					</li>
					<li>
						<a href="#">Ödevler</a>
					</li>
				
</div>
    <div class="row-fluid sortable">		
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-user"></i> Ödevler</h2>
                            <div class="box-icon">
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                    <div class="box-content">
                            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                              <thead>
                                      <tr>
                                              <th>Başlık</th>
                                              <th></th>
                                      </tr>
                              </thead>   
                              <tbody>
                                  <?php if(count($this->homeworks)){
                                      $datetimemodel = new Application_Model_Datetime();
                                      foreach ($this->homeworks as $homework) {
                                   ?>
                                    <tr>
                                            <td><?php echo $homework->title;?></td>
                                            <td class="center">
                                                    <a class="btn btn-success" href="<?php echo $this->baseUrl('/teacher/homework/show/'.$homework->id);?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Detaylı Gör
                                                    </a>
                                                    <a class="btn btn-info" href="<?php echo $this->baseUrl('/teacher/homework/edit/'.$homework->id);?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Düzenle                                          
                                                    </a>
                                                    <a class="btn btn-danger" href="<?php echo $this->baseUrl('/teacher/homework/pdf-download/'.$homework->id);?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Pdf Olarak İndir                                           
                                                    </a>
                                                <?php if(!$datetimemodel->is_accessible($homework->finish_time)){ ?>
                                                    
                                                    <a title="Ödevleri toplu halde zip olarak indir" class="btn btn-danger" href="<?php echo $this->baseUrl('/teacher/homework/homeworks-download/'.$homework->id);?>">
                                                            <i class="icon-trash icon-white"></i> 
                                                            Sonuçları İndir
                                                    </a>
                                                <?php } ?>
                     
                                            </td>
                                    </tr>
                                  <?php  }};?>
                              </tbody>
                      </table>            
                    </div>
            </div><!--/span-->

    </div><!--/row-->
    
    <div class="row-fluid sortable">
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-edit"></i>Ödev Ekle</h2>
                              <div class="box-icon">
                                    <a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                <div class="box-content">
                              <fieldset>
                                  <?php echo $this->partial('_partial/addhomework.phtml', 'teacher', array('lesson' => $this->lesson,'user' => $this->user));?>
                              </fieldset>

                    </div>
            </div><!--/span-->

</div><!--/row-->
