<html>
    <head>
        
    </head>
    <style>
        body { 
            background: url('/img/pdf_background.jpg');
            background-repeat:no-repeat;
            background-attachment:fixed;
            background-position:center; 
        }
    </style>
    <body>
         <fieldset>
                                  Son Tarih : <?php echo $this->homework->hw_finish_time; ?> <br>
                                  <h3 style="text-align: center">
                                      <?php echo $this->homework->department_name; ?><br>
                                      <?php echo $this->homework->class_name; ?><br>
                                      <?php echo $this->homework->lesson_name; ?> Dersi <br>
                                      Öğr. Görevlisi : <?php echo $this->homework->teacher_name." ". $this->homework->teacher_surname; ?>  <hr>
                                      <?php echo $this->homework->hw_title; ?>
                                  </h3>
                                  <div>
                                      <?php echo $this->homework->hw_detail;?>
                                  </div>
                              </fieldset>

    </body>
</html>