<div>
				<ul class="breadcrumb">
					<li>
						<a href="#">Anasayfa</a> <span class="divider">/</span>
					</li>
					<li>
						<a href="#">Ödev Detayları</a>
					</li>
                                </ul>
				
</div>
 
<div class="row-fluid sortable">
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-edit"></i>Ödev Detayları</h2>
                              <div class="box-icon">
                                    <a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                <div class="box-content">
                              <fieldset class="well">
                                  Son Tarih : <?php echo $this->homework->hw_finish_time; ?> <br>
                                  <h3 class="well" style="text-align: center">
                                      <?php echo $this->homework->department_name; ?><br>
                                      <?php echo $this->homework->class_name; ?><br>
                                      <?php echo $this->homework->lesson_name; ?> Dersi <br>
                                      Öğr. Görevlisi : <?php echo $this->homework->teacher_name." ". $this->homework->teacher_surname; ?>  <hr>
                                      <?php echo $this->homework->hw_title; ?>
                                  </h3>
                                  <div class="well">
                                      <?php echo $this->homework->hw_detail;?>
                                  </div>
                              </fieldset>

                    </div>
            </div><!--/span-->

</div><!--/row-->