    <div class="row-fluid sortable">		
        <div class="box span12">
                <div class="box-header well" data-original-title>
                        <h2>Son Duyurular</h2>
                        <div class="box-icon">
                                <a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
                                <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                        </div>
                </div>
                <div class="box-content">
                        <table class="table table-striped">
                                  <thead>
                                          <tr>
                                                  <th>Gönderen</th>
                                                  <th>Başlık</th>
                                                  <th>Gönderilme Zamanı</th>   
                                                  <th>Gönderilme Yeri</th>                                     
                                                  <th></th>                                          
                                          </tr>
                                  </thead>   
                                  <tbody>
            <?php
            $memberModel = new Application_Model_DbTable_Members();
            $lessonModel = new Application_Model_DbTable_Lesson();
            $departmentModel = new Application_Model_DbTable_Department();
            $classModel = new Application_Model_DbTable_Class();
            $dateModel = new Application_Model_Datetime();
            
            if(isset($this->announcements)){
            
            foreach ($this->announcements as $announcement) {
                    $teacher = $memberModel->getByFilter(array('id' => $announcement->teacher_id));
                    $sendPlace = null;
                    if($announcement->lesson_id != 0){
                        $sendPlace = $departmentModel->getByFilter(array('id'=> $announcement->department_id ))->name;
                        $sendPlace .= " - ". $classModel->getByFilter(array('id'=> $announcement->class_id ))->name;
                        $sendPlace .= " - ". $lessonModel->getByFilter(array('id'=> $announcement->lesson_id ))->name;
                    }elseif ($announcement->class_id != 0) {
                        $sendPlace = $departmentModel->getByFilter(array('id'=> $announcement->department_id ))->name;
                        $sendPlace .= " - ". $classModel->getByFilter(array('id'=> $announcement->class_id ))->name;
                    }elseif ($announcement->department_id != 0) {
                        $sendPlace = $departmentModel->getByFilter(array('id'=> $announcement->department_id ))->name;
                    }else{
                       $sendPlace = "Her Yer"; 
                    }
            ?>    
                                        <tr>
                                                <td><?php echo ucfirst($teacher->name)." ".strtoupper($teacher->surname);?></td>
                                                <td class="center"><?php echo $announcement->title;?></td>
                                                <td class="center"><?php echo $announcement->time;?></td>                                       
                                                <td class="center"><?php echo $sendPlace;?></td>                                       
                                               <td><a href="<?php echo $this->baseUrl('/student/announcement/show/'.$announcement->id);?>" class="btn btn-primary">Görüntüle</a></td>
                                        </tr>
            <?php }} ?>
                                  </tbody>
                         </table>  
                </div>
        </div><!--/span-->
</div><!--/row-->
                        
    <div class="row-fluid sortable">
            <div class="box span6">
                    <div class="box-header well" data-original-title>
                            <h2>Sıradaki Ödevler</h2>
                            <div class="box-icon">
                                    <a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                    <div class="box-content">
                            <table class="table">
                                      <thead>
                                              <tr>
                                                      <th>Bitiş</th>
                                                      <th>Ders</th>
                                                      <th>Sınıf</th>
                                                      <th>Ödev</th>
                                                      <th>Kalan Süre</th>                                          
                                              </tr>
                                      </thead>   
                               <?php 
                                   //exam görüntülemede de kullanıyoruz aşağıda.
                                   $dateModel = new Application_Model_Datetime();
                                   if(count($this->homeworks)){
                                    foreach($this->homeworks as $homework){
                                 
                                 ?>
                                            <tr>
                                                <td class="center"><?php echo $homework->hw_finish_time;?></td>
                                                <td><?php echo $homework->lesson_name;?></td>
                                                <td><?php echo $homework->class_name;?></td>
                                                <td><?php echo $homework->hw_title;?></td>
                                                <td class="center"><?php echo $dateModel->remainingTime($homework->hw_finish_time);?></td>
                                            </tr> 
                               <?php
                                        }
                                    }
                               ?>
                             </table>  
                    </div>
            </div><!--/span-->

            <div class="box span6">
                    <div class="box-header well" data-original-title>
                            <h2>Sıradaki Sınavlar</h2>
                            <div class="box-icon">
                                    <a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                    <div class="box-content">
                            <table class="table table-striped">
                                      <thead>
                                              <tr>
                                                      <th>Başlangıç</th>
                                                      <th>Bitiş</th>
                                                      <th>Ders</th>
                                                      <th>Sınıf</th>
                                                      <th>Sınav</th>
                                                      <th>Kalan Süre</th>                                            
                                              </tr>
                                      </thead>   
                                      <tbody>
                                 <?php
                                  if(count($this->exams)){
                                     foreach($this->exams as $exam){
                                 ?>
                                            <tr>
                                                    <td><?php echo $exam->exam_start_time?></td>
                                                    <td><?php echo $exam->exam_finish_time?></td>
                                                    <td><?php echo $exam->lesson_name?></td>
                                                    <td><?php echo $exam->class_name?></td>
                                                    <td><?php echo $exam->exam_title?></td>
                                                    <td><?php echo $dateModel->remainingTime($exam->exam_start_time)?></td>
                                            </tr> 
                               <?php
                                            }
                                        }
                               ?>
                                      </tbody>
                             </table>  
                    </div>
            </div><!--/span-->
    </div><!--/row-->
