<div>
				<ul class="breadcrumb">
					<li>
						<a href="#">Anasayfa</a> <span class="divider">/</span>
					</li>
					<li>
						<a href="#">Sınavlar</a>
					</li>
                                </ul>
				
</div>
    <div class="row-fluid sortable">		
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-user"></i>Sınavlar</h2>
                            <div class="box-icon">
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                    <div class="box-content">
                            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                              <thead>
                                      <tr>
                                              <th>Ders</th>
                                              <th>Öğretim Görevlisi</th>
                                              <th>Başlık</th>
                                              <th>Başlangıç</th>
                                              <th>Bitiş</th>
                                              <th></th>
                                      </tr>
                              </thead>   
                              <tbody>
                                  <?php if(count($this->exams)){
                                    $memberModel = new Application_Model_DbTable_Members();
                                    $lessonModel = new Application_Model_DbTable_Lesson();
                                    foreach ($this->exams as $exam) {
                                        $teacher = $memberModel->getByFilter(array('id' => $exam->teacher_id));
                                  ?>


                                    <tr>
                                        <td class="center"><?php echo $lessonModel->getByFilter(array('id' => $exam->lesson_id))->name;?></td>
                                            <td class="center"><?php echo $teacher->name." ".$teacher->surname; ?></td>
                                            <td class="center"><?php echo $exam->title; ?></td>
                                            <td class="center"><?php echo $exam->start_time; ?></td>
                                            <td class="center"><?php echo $exam->finish_time; ?></td>
                                            <td class="center">
                                                    <a class="btn btn-success" href="<?php echo $this->baseUrl('/student/exam/show/'.$exam->id);?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Görüntüle                                            
                                                    </a>
                                            </td>
                                    </tr>
                                  <?php  }};?>
                              </tbody>
                      </table>            
                    </div>
            </div><!--/span-->

    </div><!--/row-->
