<?php
echo "<h1>Site Map</h1>";
    foreach ($this->acl as $modulename => $module) {
        echo "<h4 style='color:brown'>" . strtoupper($modulename) . "</h4>";
        foreach($module as $controllername => $controller){
            echo "~ ~ ~ ~ ";
            echo "<strong>". ucfirst($controllername) . "</strong>";
            foreach($controller as $actionname){
               echo "<br>~ ~ ~ ~ ~ ~ ~ ~";
               echo ucfirst($actionname);
            }   
            echo "<br>";
        }
    }