<div>
				<ul class="breadcrumb">
					<li>
						<a href="#">Anasayfa</a> <span class="divider">/</span>
					</li>
					<li>
                                            <a href="#"><?php echo ucfirst($this->departmentName);?></a><span class="divider">/</span>
					</li>
					<li>
						<a href="#">Dersler</a>
					</li>
				
</div>
    <div class="row-fluid sortable">		
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-user"></i> Dersler</h2>
                            <div class="box-icon">
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                    <div class="box-content">
                            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                              <thead>
                                      <tr>
                                              <th>Adı</th>
                                              <th>Sınıfı</th>
                                              <th>Öğretim Görevlisi</th>
                                              <th></th>
                                      </tr>
                              </thead>   
                              <tbody>
                                  <?php if(count($this->lessonsWithTeacher)){
                                      foreach ($this->lessonsWithTeacher as $lesson) {
                                       ?>
                                    
                                    <tr>
                                            <td class="center"><?php echo $lesson->les_name;?></td>
                                            <td class="center"><?php echo ucfirst($lesson->class_name);?></td>
                                            <td class="center"><?php echo $lesson->teac_name." ".$lesson->teac_surname?></td>
                                            <td class="center">
                                                    <a class="btn btn-success" href="<?php echo $this->baseUrl('/teacher/lesson/lesson-students/'.$lesson->les_id);?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Derse Kaydol                                            
                                                    </a>
                                            </td>
                                    </tr>
                                  <?php  }};?>
                      
                                <?php if(count($this->lessonsWithNoTeacher)){
                                      foreach ($this->lessonsWithNoTeacher as $lesson) {
                                       ?>
                                    
                                    <tr>
                                            <td class="center"><?php echo $lesson->les_name;?></td>
                                            <td class="center"><?php echo ucfirst($lesson->class_name);?></td>
                                            <td class="center">Atanmadı</td>
                                            <td class="center">
                                                    <?php
                                                    $studentLessonModel = new Application_Model_DbTable_LessonStudent();
                                                    $status = $studentLessonModel->getByFilter(array('student_id' => $this->user->id,'lesson_id' => $lesson->les_id));
                                                    if(!count($status)){ ?>
                                                        
                                                        <a class="btn btn-success" href="<?php echo $this->baseUrl('/student/lesson/add-lesson-application/'.$lesson->les_id);?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Derse Kaydol                                            
                                                        </a>
                                                    <?php
                                                         
                                                    }
                                                    ?>                                                    
                                            </td>
                                    </tr>
                                  <?php  }}?>
                                    
                                    
                        </tbody>
                      </table>            
                    </div>
            </div><!--/span-->

    </div><!--/row-->
