<div>
				<ul class="breadcrumb">
					<li>
						<a href="#">Anasayfa</a> <span class="divider">/</span>
					</li>
					<li>
                                            <a href="#">Verdiğim Dersler</a><span class="divider">/</span>
					</li>
					<li>
						<a href="#">Dersler</a>
					</li>
				
</div>
    <div class="row-fluid sortable">		
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-user"></i> Dersler</h2>
                            <div class="box-icon">
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                    <div class="box-content">
                            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                              <thead>
                                      <tr>
                                              <th>Adı</th>
                                              <th>Sınıfı</th>
                                              <th>Öğretim Görevlisi</th>
                                              <th></th>
                                      </tr>
                              </thead>   
                              <tbody>
                                  <?php if(count($this->lessons)){
                                      $memberModel = new Application_Model_DbTable_Members();
                                      $classModel = new Application_Model_DbTable_Class();
                                      $lessonModel = new Application_Model_DbTable_Lesson();
                                      foreach ($this->lessons as $lesson) {
                                            $thisLesson = $lessonModel->getByFilter(array('id' => $lesson->lesson_id));
                                       ?>
                                    
                                    <tr>
                                            <td><?php echo $thisLesson->name; ?></td>
                                            <td><?php echo $classModel->getByFilter(array('id' => $thisLesson->class_id))->name ;?></td>
                                            <td class="center"><?php echo $memberModel->getByFilter(array('id' => $thisLesson->teacher_id))->name?></td>
                                            <td class="center">
                                                    <a class="btn btn-success" href="<?php echo $this->baseUrl('/student/homework/lesson-homeworks/'.$lesson->lesson_id);?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Ödevler                                            
                                                    </a>
                                                    <a class="btn btn-info" href="<?php echo $this->baseUrl('/student/exam/lesson-exams/'.$lesson->lesson_id);?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Sınavlar                                            
                                                    </a>
                                            </td>
                                    </tr>
                                  <?php  }};?>
                              </tbody>
                      </table>            
                    </div>
            </div><!--/span-->

    </div><!--/row-->