<div>
				<ul class="breadcrumb">
					<li>
						<a href="#">Anasayfa</a> <span class="divider">/</span>
					</li>
					<li>
						<a href="#">Onay Bekleyen Öğrenciler</a>
					</li>
				
</div>
    <div class="row-fluid sortable">		
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-user"></i>Onay Bekleyen Öğrenciler</h2>
                            <div class="box-icon">
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                    <div class="box-content">
                            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                              <thead>
                                      <tr>
                                              <th>İsim</th>
                                              <th>Soyisim</th>
                                              <th>Numara</th>
                                              <th>Bölüm</th>
                                              <th>Sınıf</th>
                                              <th>Kayıt Zamanı</th>
                                              <th></th>
                                      </tr>
                              </thead>   
                              <tbody>
                                  <?php if(count($this->waitingStudents)){
                                    foreach ($this->waitingStudents as $student) { ?>


                                    <tr>
                                            <td class="center"><?php echo $student->student_name ?></td>
                                            <td class="center"><?php echo $student->student_surname?></td>
                                            <td class="center"><?php echo $student->student_number?></td>
                                            <td class="center"><?php echo $student->department_name ?></td>
                                            <td class="center"><?php echo $student->class_name ?></td>
                                            <td class="center"><?php echo $student->student_created?></td>
                                            <td class="center">
                                                    <a class="btn btn-success" href="<?php echo $this->baseUrl('/teacher/department-students/confirmed-student/'.$student->student_id);?>">
                                                            <i class="icon-edit icon-white"></i>  
                                                            Onayla                                  
                                                    </a>
                                                    <a class="btn btn-danger" href="<?php echo $this->baseUrl('/teacher/department-students/delete-student/'.$student->student_id) ?>">
                                                            <i class="icon-trash icon-white"></i> 
                                                            Sil
                                                    </a>
                                            </td>
                                    </tr>
                                  <?php  }};?>
                              </tbody>
                      </table>            
                    </div>
            </div><!--/span-->

    </div><!--/row-->