<div>
				<ul class="breadcrumb">
					<li>
						<a href="#">Anasayfa</a> <span class="divider">/</span>
					</li>
					<li>
						<a href="#">Onay Bekleyen Öğrenciler</a>
					</li>
				
</div>
    <div class="row-fluid sortable">		
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-user"></i> Öğrenciler</h2>
                            <div class="box-icon">
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                    <div class="box-content">
                            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                              <thead>
                                      <tr>
                                              <th>İsim</th>
                                              <th>Soyisim</th>
                                              <th>Bölüm</th>
                                              <th>Sınıf</th>
                                              <th>Ders</th>
                                              <th>Kayıt Zamanı</th>
                                              <th></th>
                                      </tr>
                              </thead>   
                              <tbody>
                                  <?php if(count($this->waitingStudents)){
                                    $departmentModel = new Application_Model_DbTable_Department();
                                    $classModel = new Application_Model_DbTable_Class();
                                    $lessonModel = new Application_Model_DbTable_Lesson();
                                    $memberModel = new Application_Model_DbTable_Members();
                                    foreach ($this->waitingStudents as $result) { 
                                        $student = $memberModel->getByFilter(array('id' => $result->student_id));
                                     ?>
                                        
                                    <tr>
                                            <td class="center"><?php echo $student->name; ?></td>
                                            <td class="center"><?php echo $student->surname; ?></td>
                                            <td class="center"><?php echo $departmentModel->getByFilter(array('id' => $student->department_id))->name; ?></td>
                                            <td class="center"><?php echo $classModel->getByFilter(array('id' => $student->class_id))->name; ?></td>
                                            <td class="center"><?php echo $lessonModel->getByFilter(array('id' => $result->lesson_id))->name; ?></td>
                                            <td class="center"><?php echo $result->time; ?></td>
                                            <td class="center">
                                                    <a class="btn btn-success" href="<?php echo $this->baseUrl('/teacher/lesson/confirmed-student-lesson-application/'.$result->lesson_id."/".$result->student_id);?>">
                                                            <i class="icon-edit icon-white"></i>  
                                                            Onayla                                  
                                                    </a>
                                                    <a class="btn btn-danger" href="<?php echo $this->baseUrl('/teacher/lesson/delete-student-lesson-application/'.$result->lesson_id."/".$result->student_id);?>">
                                                            <i class="icon-trash icon-white"></i> 
                                                            Sil
                                                    </a>
                                            </td>
                                    </tr>
                                  <?php  }};?>
                              </tbody>
                      </table>            
                    </div>
            </div><!--/span-->

    </div><!--/row-->