<div class="span2 main-menu-span">
       <div class="well nav-collapse sidebar-nav">
                <ul class="nav nav-tabs nav-stacked main-menu">
                        <li class="nav-header hidden-tablet">Menu</li>
                        <li><a class="ajax-link" href="<?php echo $this->baseUrl();?>"><i class="icon-home"></i><span class="hidden-tablet"> Anasayfa</span></a></li>
                        <li><a class="ajax-link" href="<?php echo $this->baseUrl();?>/student/lesson"><i class="icon-eye-open"></i><span class="hidden-tablet">Derslerim</span></a></li>
                        <li><a class="ajax-link" href="<?php echo $this->baseUrl();?>/student/homework""><i class="icon-edit"></i><span class="hidden-tablet">Ödevlerim</span></a></li>
                        <li><a class="ajax-link" href="<?php echo $this->baseUrl();?>/student/announcement/"><i class="icon-list-alt"></i><span class="hidden-tablet">Duyurular</span></a></li>
                        <li><a class="ajax-link" href="<?php echo $this->baseUrl();?>/student/exam/"><i class="icon-list-alt"></i><span class="hidden-tablet">Sınavlar</span></a></li>
                        <li><a class="ajax-link" href="<?php echo $this->baseUrl();?>/student/lesson/department-lessons/"><i class="icon-list-alt"></i><span class="hidden-tablet">Bölüm Dersleri</span></a></li>
                        <li><a class="ajax-link" href="typography.html"><i class="icon-font"></i><span class="hidden-tablet">Danışman İle İletişim</span></a></li>
                        <label id="for-is-ajax" class="hidden-tablet" for="is-ajax"><a href="<?php echo $this->baseUrl();?>/student/index/logout">Çıkış</a></label>
        </div><!--/.well -->
</div><!--/span-->
