<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<!--- Select Menu Jquery Kodlamaları --->
<script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
<script>
function work(){
    var department_id = $("#department_id").val();
    var class_id = $("#class_id").val();
    $.getJSON('/admin/announcement/get-json?department_id='+department_id+"&class_id="+class_id, function(data) {
        var output="";
        for (var i in data) {
            output+="<option value='"+ data[i].id+"'>"+ data[i].name+"</select>";
        }
        document.getElementById("lesson_id").innerHTML=output;
  });
}
$(document).ready(function(){
     work();
     $('#department_id').change(function(){
            work();
     });
     $('#class_id').change(function(){
            work();
     });
});
</script>

<div>
				<ul class="breadcrumb">
					<li>
						<a href="#">Anasayfa</a> <span class="divider">/</span>
					</li>
					<li>
						<a href="#">Duyurular</a>
					</li>
				
</div>
    <div class="row-fluid sortable">		
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-user"></i>Tüm Duyurular</h2>
                            <div class="box-icon">
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                    <div class="box-content">
                            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                              <thead>
                                      <tr>
                                              <th>Bölüm</th>
                                              <th>Sınıf</th>
                                              <th>Ders</th>
                                              <th>Başlık</th>
                                              <th>Duyuru</th>
                                              <th>Gönd. Zamanı</th>
                                              <th></th>
                                      </tr>
                              </thead>   
                              <tbody>
                                  <?php if(count($this->announcements_with_class)){
                                    foreach ($this->announcements_with_class as $announcement) { ?>


                                    <tr>
                                            <td class="center"><?php echo $announcement->department_name?></td>
                                            <td class="center"><?php echo $announcement->class_name?></td>
                                            <td class="center">Bütün Dersler</td>
                                            <td class="center"><?php echo substr($announcement->ann_title, 0, 60)?></td>
                                            <td class="center"><?php echo substr($announcement->ann_detail, 0, 60)?></td>
                                            <td class="center"><?php echo $announcement->ann_time; ?></td>
                                            <td class="center">
                                                    <a class="btn btn-success" href="<?php echo $this->baseUrl('/admin/announcement/show/'.$announcement->ann_id);?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Görüntüle                                            
                                                    </a>
                                                    <a class="btn btn-info" href="<?php echo $this->baseUrl('/admin/announcement/edit/'.$announcement->ann_id);?>">
                                                            <i class="icon-edit icon-white"></i>  
                                                            Düzenle                                            
                                                    </a>
                                                    <a class="btn btn-danger" href="<?php echo $this->baseUrl('/admin/announcement/delete/'.$announcement->ann_id);?>">
                                                            <i class="icon-trash icon-white"></i> 
                                                            Sil
                                                    </a>
                                            </td>
                                    </tr>
                                  <?php  }};?>
                                    
                                    
                                 <?php if(count($this->announcements_with_lesson)){
                                    foreach ($this->announcements_with_lesson as $announcement) { ?>


                                    <tr>
                                            <td class="center"><?php echo $announcement->department_name?></td>
                                            <td class="center"><?php echo $announcement->class_name?></td>
                                            <td class="center"><?php echo $announcement->lesson_name?></td>
                                            <td class="center"><?php echo substr($announcement->ann_title, 0, 60)?></td>
                                            <td class="center"><?php echo substr($announcement->ann_detail, 0, 60)?></td>
                                            <td class="center"><?php echo $announcement->ann_time; ?></td>
                                            <td class="center">
                                                    <a class="btn btn-success" href="<?php echo $this->baseUrl('/admin/announcement/show/'.$announcement->ann_id);?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Görüntüle                                            
                                                    </a>
                                                    <a class="btn btn-info" href="<?php echo $this->baseUrl('/admin/announcement/edit/'.$announcement->ann_id);?>">
                                                            <i class="icon-edit icon-white"></i>  
                                                            Düzenle                                            
                                                    </a>
                                                    <a class="btn btn-danger" href="<?php echo $this->baseUrl('/admin/announcement/delete/'.$announcement->ann_id);?>">
                                                            <i class="icon-trash icon-white"></i> 
                                                            Sil
                                                    </a>
                                            </td>
                                    </tr>
                                  <?php  }};?>
                                    
                                 
                                 <?php if(count($this->announcements_with_department)){
                                    foreach ($this->announcements_with_department as $announcement) { ?>


                                    <tr>
                                            <td class="center"><?php echo $announcement->department_name?></td>
                                            <td class="center">Bütün Sınıflar</td>
                                            <td class="center">Bütün Dersler</td>
                                            <td class="center"><?php echo substr($announcement->ann_title, 0, 60)?></td>
                                            <td class="center"><?php echo substr($announcement->ann_detail, 0, 60)?></td>
                                            <td class="center"><?php echo $announcement->ann_time; ?></td>
                                            <td class="center">
                                                    <a class="btn btn-success" href="<?php echo $this->baseUrl('/admin/announcement/show/'.$announcement->ann_id);?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Görüntüle                                            
                                                    </a>
                                                    <a class="btn btn-info" href="<?php echo $this->baseUrl('/admin/announcement/edit/'.$announcement->ann_id);?>">
                                                            <i class="icon-edit icon-white"></i>  
                                                            Düzenle                                            
                                                    </a>
                                                    <a class="btn btn-danger" href="<?php echo $this->baseUrl('/admin/announcement/delete/'.$announcement->ann_id);?>">
                                                            <i class="icon-trash icon-white"></i> 
                                                            Sil
                                                    </a>
                                            </td>
                                    </tr>
                                  <?php  }};?>
                             
                              
                               <?php if(count($this->announcements)){
                                    foreach ($this->announcements as $announcement) { ?>
                                    <tr>
                                            <td class="center">Bütün Bölümler</td>
                                            <td class="center">Bütün Sınıflar</td>
                                            <td class="center">Bütün Dersler</td>
                                            <td class="center"><?php echo substr($announcement->ann_title, 0, 60)?></td>
                                            <td class="center"><?php echo substr($announcement->ann_detail, 0, 60)?></td>
                                            <td class="center"><?php echo $announcement->ann_time; ?></td>
                                            <td class="center">
                                                    <a class="btn btn-success" href="<?php echo $this->baseUrl('/admin/announcement/show/'.$announcement->ann_id);?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Görüntüle                                            
                                                    </a>
                                                    <a class="btn btn-info" href="<?php echo $this->baseUrl('/admin/announcement/edit/'.$announcement->ann_id);?>">
                                                            <i class="icon-edit icon-white"></i>  
                                                            Düzenle                                            
                                                    </a>
                                                    <a class="btn btn-danger" href="<?php echo $this->baseUrl('/admin/announcement/delete/'.$announcement->ann_id);?>">
                                                            <i class="icon-trash icon-white"></i> 
                                                            Sil
                                                    </a>
                                            </td>
                                    </tr>
                                  <?php  }};?>
                             </tbody>
                      </table>            
                    </div>
            </div><!--/span-->

    </div><!--/row-->
    <div class="row-fluid sortable">		
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-user"></i>Yaptığım Duyurular</h2>
                            <div class="box-icon">
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                    <div class="box-content">
                            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                              <thead>
                                      <tr>
                                              <th>Bölüm</th>
                                              <th>Sınıf</th>
                                              <th>Ders</th>
                                              <th>Başlık</th>
                                              <th>Duyuru</th>
                                              <th>Gönd. Zamanı</th>
                                              <th></th>
                                      </tr>
                              </thead>   
                              <tbody>
                                  
                                  <?php if(count($this->my_announcements_with_class)){
                                    foreach ($this->my_announcements_with_class as $announcement) { ?>


                                    <tr>
                                            <td class="center"><?php echo $announcement->department_name?></td>
                                            <td class="center"><?php echo $announcement->class_name?></td>
                                            <td class="center">Bütün Dersler</td>
                                            <td class="center"><?php echo substr($announcement->ann_title, 0, 60)?></td>
                                            <td class="center"><?php echo substr($announcement->ann_detail, 0, 60)?></td>
                                            <td class="center"><?php echo $announcement->ann_time; ?></td>
                                            <td class="center">
                                                    <a class="btn btn-success" href="<?php echo $this->baseUrl('/admin/announcement/show/'.$announcement->ann_id);?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Görüntüle                                            
                                                    </a>
                                                    <a class="btn btn-info" href="<?php echo $this->baseUrl('/admin/announcement/edit/'.$announcement->ann_id);?>">
                                                            <i class="icon-edit icon-white"></i>  
                                                            Düzenle                                            
                                                    </a>
                                                    <a class="btn btn-danger" href="<?php echo $this->baseUrl('/admin/announcement/delete/'.$announcement->ann_id);?>">
                                                            <i class="icon-trash icon-white"></i> 
                                                            Sil
                                                    </a>
                                            </td>
                                    </tr>
                                  <?php  }};?>
                                    
                                    
                                 <?php if(count($this->my_announcements_with_lesson)){
                                    foreach ($this->my_announcements_with_lesson as $announcement) { ?>


                                    <tr>
                                            <td class="center"><?php echo $announcement->department_name?></td>
                                            <td class="center"><?php echo $announcement->class_name?></td>
                                            <td class="center"><?php echo $announcement->lesson_name?></td>
                                            <td class="center"><?php echo substr($announcement->ann_title, 0, 60)?></td>
                                            <td class="center"><?php echo substr($announcement->ann_detail, 0, 60)?></td>
                                            <td class="center"><?php echo $announcement->ann_time; ?></td>
                                            <td class="center">
                                                    <a class="btn btn-success" href="<?php echo $this->baseUrl('/admin/announcement/show/'.$announcement->ann_id);?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Görüntüle                                            
                                                    </a>
                                                    <a class="btn btn-info" href="<?php echo $this->baseUrl('/admin/announcement/edit/'.$announcement->ann_id);?>">
                                                            <i class="icon-edit icon-white"></i>  
                                                            Düzenle                                            
                                                    </a>
                                                    <a class="btn btn-danger" href="<?php echo $this->baseUrl('/admin/announcement/delete/'.$announcement->ann_id);?>">
                                                            <i class="icon-trash icon-white"></i> 
                                                            Sil
                                                    </a>
                                            </td>
                                    </tr>
                                  <?php  }};?>
                                    
                                 
                                 <?php if(count($this->my_announcements_with_department)){
                                    foreach ($this->my_announcements_with_department as $announcement) { ?>


                                    <tr>
                                            <td class="center"><?php echo $announcement->department_name?></td>
                                            <td class="center">Bütün Sınıflar</td>
                                            <td class="center">Bütün Dersler</td>
                                            <td class="center"><?php echo substr($announcement->ann_title, 0, 60)?></td>
                                            <td class="center"><?php echo substr($announcement->ann_detail, 0, 60)?></td>
                                            <td class="center"><?php echo $announcement->ann_time; ?></td>
                                            <td class="center">
                                                    <a class="btn btn-success" href="<?php echo $this->baseUrl('/admin/announcement/show/'.$announcement->ann_id);?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Görüntüle                                            
                                                    </a>
                                                    <a class="btn btn-info" href="<?php echo $this->baseUrl('/admin/announcement/edit/'.$announcement->ann_id);?>">
                                                            <i class="icon-edit icon-white"></i>  
                                                            Düzenle                                            
                                                    </a>
                                                    <a class="btn btn-danger" href="<?php echo $this->baseUrl('/admin/announcement/delete/'.$announcement->ann_id);?>">
                                                            <i class="icon-trash icon-white"></i> 
                                                            Sil
                                                    </a>
                                            </td>
                                    </tr>
                                  <?php  }};?>
                             
                              
                               <?php if(count($this->my_announcements)){
                                    foreach ($this->my_announcements as $announcement) { ?>
                                    <tr>
                                            <td class="center">Bütün Bölümler</td>
                                            <td class="center">Bütün Sınıflar</td>
                                            <td class="center">Bütün Dersler</td>
                                            <td class="center"><?php echo substr($announcement->ann_title, 0, 60)?></td>
                                            <td class="center"><?php echo substr($announcement->ann_detail, 0, 60)?></td>
                                            <td class="center"><?php echo $announcement->ann_time; ?></td>
                                            <td class="center">
                                                    <a class="btn btn-success" href="<?php echo $this->baseUrl('/admin/announcement/show/'.$announcement->ann_id);?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Görüntüle                                            
                                                    </a>
                                                    <a class="btn btn-info" href="<?php echo $this->baseUrl('/admin/announcement/edit/'.$announcement->ann_id);?>">
                                                            <i class="icon-edit icon-white"></i>  
                                                            Düzenle                                            
                                                    </a>
                                                    <a class="btn btn-danger" href="<?php echo $this->baseUrl('/admin/announcement/delete/'.$announcement->ann_id);?>">
                                                            <i class="icon-trash icon-white"></i> 
                                                            Sil
                                                    </a>
                                            </td>
                                    </tr>
                                  <?php  }};?>
                              </tbody>
                      </table>            
                    </div>
            </div><!--/span-->

    </div><!--/row-->

    <div class="row-fluid sortable">
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-edit"></i>Duyuru Ekle</h2>
                              <div class="box-icon">
                                    <a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                <div class="box-content">
                              <fieldset>
                                    <?php echo $this->form;?>
                              </fieldset>

                    </div>
            </div><!--/span-->

</div><!--/row-->
<div id='test'></div>
<!-- Acılır menü icin javascript kodlarımı-->

    