<center>
    <fieldset>
        <legend>
            <?php echo $this->translate('New User Account') ;?>
        </legend>
        <a class="btn btn-primary"  href="<?php echo $this->baseUrl();?>/index/studentsignup"><?php echo $this->translate('Student') ;?></a><br /><br />
        <a class="btn btn-primary" href="<?php echo $this->baseUrl();?>/index/teachersignup"><?php echo $this->translate('Teacher') ;?></a><br /><br >
    </fieldset>
</center>