    <div class="container-fluid">
        <center>
            <fieldset style="width: 200px">
                <legend>Öğrenci Kayıt Menüsü</legend>
             <?php echo $this->form;?>
            </form>
                <a href="<?php echo $this->baseUrl().'/default/teacher/signup';?>">Henüz kayıtlı değil misin.? Kaydolmak için tıkla...</a>
            </fieldset>
        </center><br><br><br>
    </div>

