    <div class="container-fluid" style="margin-left: 25%">
            <fieldset style="width: 50%">
                <legend>Öğrenci Kayıt Menüsü</legend>
             <?php echo $this->form;?>
            </form>
                <a href="<?php echo $this->baseUrl().'/default/teacher/signup';?>">Henüz kayıtlı değil misin.? Kaydolmak için tıkla...</a>
            </fieldset>
        <br><br><br>
    </div>

