<div>
				<ul class="breadcrumb">
					<li>
						<a href="#">Anasayfa</a> <span class="divider">/</span>
					</li>
					<li>
                                            <a href="#">Verdiğim Dersler</a><span class="divider">/</span>
					</li>
					<li>
						<a href="#">Dersler</a>
					</li>
				
</div>
    <div class="row-fluid sortable">		
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-user"></i> Dersler</h2>
                            <div class="box-icon">
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                    <div class="box-content">
                            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                              <thead>
                                      <tr>
                                              <th>Adı</th>
                                              <th>Bölüm</th>
                                              <th>Sınıfı</th>
                                              <th></th>
                                      </tr>
                              </thead>   
                              <tbody>
                                  <?php if(count($this->lessons)){
                                      foreach ($this->lessons as $lesson) {
                                       ?>
                                    
                                    <tr>
                                            <td class="center"><?php echo $lesson->les_name; ?></td>
                                            <td><?php echo $lesson->department_name;?></td>
                                            <td class="center"><?php echo ucfirst($lesson->class_name);?></td>
                                            <td class="center">
                                                    <a class="btn btn-success" href="<?php echo $this->baseUrl('/teacher/lesson/lesson-students/'.$lesson->les_id);?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Alan Öğrenciler                                            
                                                    </a>
                                                    <a class="btn btn-success" href="<?php echo $this->baseUrl('/teacher/homework/lesson-homeworks/'.$lesson->les_id);?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Ödevler                                            
                                                    </a>
                                                    <a class="btn btn-success" href="<?php echo $this->baseUrl('/teacher/exams/lesson-exams/'.$lesson->les_id);?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Sınavlar                                            
                                                    </a>
                                                <?php if($lesson->les_is_deleted == 'false'){ ?>
                                                    <a class="btn btn-danger" href="<?php echo $this->baseUrl().'/teacher/lesson/un-publish/' . $lesson->les_id;?>">
                                                            <i class="icon-trash icon-white"></i> 
                                                            Yayından Kaldır
                                                    </a>
                                                <?php } else { ?>
                                                    <a class="btn btn-warning" href="<?php echo $this->baseUrl().'/teacher/lesson/publish/' . $lesson->les_id;?>">
                                                            <i class="icon-trash icon-white"></i> 
                                                            Yayınla
                                                    </a>
                                                <?php }  ?>
                                                
                                                    <a class="btn btn-warning" href="<?php echo $this->baseUrl().'/teacher/lesson/student-list/' . $lesson->les_id;?>">
                                                            <i class="icon-trash icon-white"></i> 
                                                            Pdf Öğr.Listesi
                                                    </a>
                                            </td>
                                    </tr>
                                  <?php  }};?>
                              </tbody>
                      </table>            
                    </div>
            </div><!--/span-->

    </div><!--/row-->