<div>
				<ul class="breadcrumb">
					<li>
						<a href="#">Anasayfa</a> <span class="divider">/</span>
					</li>
					<li>
                                            <a href="#">Dersi Alan Öğrenciler</a><span class="divider">/</span>
					</li>
					<li>
						<a href="#">Öğrenciler</a>
					</li>
				
</div>
    <div class="row-fluid sortable">		
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-user"></i> Öğrenciler</h2>
                            <div class="box-icon">
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                    <div class="box-content">
                            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                              <thead>
                                      <tr>
                                              <th>Adı</th>
                                              <th>Soyadı</th>
                                              <th>Sınıfı</th>
                                              <th></th>
                                      </tr>
                              </thead>   
                              <tbody>
                                  <?php if(count($this->students)){
                                      foreach ($this->students as $student) {
                                       ?>
                                    
                                    <tr>
                                            <td><?php echo $student->student_name;?></td>
                                            <td><?php echo $student->student_surname;?></td>
                                            <td class="center"><?php echo $student->class_name;?></td>
                                            <td class="center">
                                                    <a class="btn btn-success" href="<?php echo $this->baseUrl('/teacher/student/show/'.$student->student_id);?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Görüntüle                                           
                                                    </a>
                                            </td>
                                    </tr>
                                  <?php  }};?>
                              </tbody>
                      </table>            
                    </div>
            </div><!--/span-->

    </div><!--/row-->