<html>
    <head>
        
    </head>
    <style>
        body { 
            background: url('/img/pdf_background.jpg');
            background-repeat:no-repeat;
            background-attachment:fixed;
            background-position:center; 
        }
    </style>
    <body>
    
    
        <h1 style='text-align: center'><?php echo $this->lesson->name."<br>"; ?></h1>
<br><br>
        <h2>Öğrenci Listesi</h2>
        <br><br>
            <table border="0">
                 <tr>
                    <td style="font-weight:bold">Öğrenci No</td>
                    <td style="font-weight:bold">İsim</td>
                    <td style="font-weight:bold">Soyisim</td>
                </tr>
                    <?php if(count($this->student_ids)){
                        $memberModel = new Application_Model_DbTable_Members();
                        foreach ($this->student_ids as $student_id) { 
                            $member = $memberModel->getByFilter(array('id' => $student_id->student_id));
                     ?>
                            <tr>
                                <td><?php echo $member->studentNumber;?></td>
                                <td><?php echo $member->name;?></td>
                                <td><?php echo $member->surname;?></td>
                            </tr>
                    <?php }
                        }; 
                    ?>
            </table>
    </body>
</html>