<div>
				<ul class="breadcrumb">
					<li>
						<a href="#">Anasayfa</a> <span class="divider">/</span>
					</li>
					<li>
						<a href="#">Bölümler</a>
					</li>
				
</div>
    <div class="row-fluid sortable">		
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-user"></i> Bölümler</h2>
                            <div class="box-icon">
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                    <div class="box-content">
                            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                              <thead>
                                      <tr>
                                              <th>Bölüm</th>
                                              <th>Başkanı</th>
                                              <th></th>
                                      </tr>
                              </thead>   
                              <tbody>
                                  <?php if(count($this->departments_with_no_teachers)){
                                    $memberModel = new Application_Model_DbTable_Members();
                                    foreach ($this->departments_with_no_teachers as $department) { ?>
                                    <tr>
                                            <td class="center"><?php echo $department->name?></td>
                                            <td class="center">Atanmadı</td>
                                            <td class="center">
                                                    <a class="btn btn-success" href="<?php echo $this->baseUrl().'/admin/department/show/' . $department->id;?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Dersler                                            
                                                    </a>
                                                    <a class="btn btn-success" href="<?php echo $this->baseUrl().'/admin/student/department-list/' . $department->id;?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Öğrenci Listeleri                                            
                                                    </a>
                                                    <a class="btn btn-success" href="<?php echo $this->baseUrl().'/admin/department/teachers/' . $department->id;?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Öğretim Görevlileri                                          
                                                    </a>
                                                     <a class="btn btn-info" href="<?php echo $this->baseUrl().'/admin/department/edit/' . $department->id;?>">
                                                            <i class="icon-edit icon-white"></i>  
                                                            Düzenle                                            
                                                    </a>
                                                <?php if($department->is_deleted == 'false'){ ?>
                                                    <a class="btn btn-danger" href="<?php echo $this->baseUrl().'/admin/department/un-publish/' . $department->id;?>">
                                                            <i class="icon-trash icon-white"></i> 
                                                            Yeni Öğrenci Kayıtlarına Kapat
                                                    </a>
                                                <?php } else { ?>
                                                    <a class="btn btn-warning" href="<?php echo $this->baseUrl().'/admin/department/publish/' . $department->id;?>">
                                                            <i class="icon-trash icon-white"></i> 
                                                            Yeni Öğrenci Kayıtlarına Aç
                                                    </a>
                                                <?php }  ?>
                                            </td>
                                    </tr>
                                  <?php  }};?>
                                    
                                    
                                    
                                  <?php if(count($this->departments_with_teachers)){
                                    foreach ($this->departments_with_teachers as $department) { ?>
                                    <tr>
                                            <td class="center"><?php echo $department->dep_name?></td>
                                            <td class="center"><?php echo $department->adv_name." ".$department->adv_surname?></td>
                                            <td class="center">
                                                    <a class="btn btn-success" href="<?php echo $this->baseUrl().'/admin/department/show/' . $department->dep_id;?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Dersler                                            
                                                    </a>
                                                    <a class="btn btn-success" href="<?php echo $this->baseUrl().'/admin/student/department-list/' . $department->dep_id;?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Öğrenci Listeleri                                            
                                                    </a>
                                                   <a class="btn btn-success" href="<?php echo $this->baseUrl().'/admin/department/teachers/' . $department->dep_id;?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Öğretim Görevlileri                                            
                                         
                                                    </a>
                                                    <a class="btn btn-info" href="<?php echo $this->baseUrl().'/admin/department/edit/' . $department->dep_id;?>">
                                                            <i class="icon-edit icon-white"></i>  
                                                            Düzenle                                            
                                                    </a>
                                                <?php if($department->dep_is_deleted == 'false'){ ?>
                                                    <a class="btn btn-danger" href="<?php echo $this->baseUrl().'/admin/department/un-publish/' . $department->dep_id;?>">
                                                            <i class="icon-trash icon-white"></i> 
                                                            Yeni Öğrenci Kayıtlarına Kapat
                                                    </a>
                                                <?php } else { ?>
                                                    <a class="btn btn-warning" href="<?php echo $this->baseUrl().'/admin/department/publish/' . $department->dep_id;?>">
                                                            <i class="icon-trash icon-white"></i> 
                                                            Yeni Öğrenci Kayıtlarına Aç
                                                    </a>
                                                <?php }  ?>
                                            </td>
                                    </tr>
                                  <?php  }};?>
                              </tbody>
                      </table>            
                    </div>
            </div><!--/span-->

    </div><!--/row-->

    <div class="row-fluid sortable">
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-edit"></i>Bölüm Ekle</h2>
                              <div class="box-icon">
                                    <a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                <div class="box-content">
                              <fieldset>
                                    <?php echo $this->form;?>
                              </fieldset>

                    </div>
            </div><!--/span-->

</div><!--/row-->
