<div>
				<ul class="breadcrumb">
					<li>
						<a href="#">Anasayfa</a> <span class="divider">/</span>
					</li>
					<li>
                                            <a href="#"><?php echo ucfirst($this->departmentName);?></a><span class="divider">/</span>
					</li>
					<li>
						<a href="#">Dersler</a>
					</li>
				
</div>
    <div class="row-fluid sortable">		
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-user"></i> Dersler</h2>
                            <div class="box-icon">
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                    <div class="box-content">
                            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                              <thead>
                                      <tr>
                                              <th>Adı</th>
                                              <th>Sınıfı</th>
                                              <th>Öğretim Görevlisi</th>
                                              <th></th>
                                      </tr>
                              </thead>   
                              <tbody>
                                  <?php
                                  //Öğretmeni olan dersler
                                  if(count($this->lessons_with_teacher)){
                                      foreach ($this->lessons_with_teacher as $lesson) {
                                  ?>
                                    
                                    <tr>
                                            <td class="center"><?php echo $lesson->les_name ;?></td>
                                            <td class="center"><?php echo ucfirst($lesson->class_name)?></td>
                                            <td class="center">
                                                <?php echo ucfirst($lesson->teac_name) . " " . strtoupper($lesson->teac_surname);
                                                ?>
                                            </td>
                                            <td class="center">
                                                    <a class="btn btn-success" href="<?php echo $this->baseUrl('/admin/lesson/lesson-students/'.$lesson->les_id);?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Alan Öğrenciler                                            
                                                    </a>
                                                    <a class="btn btn-success" href="<?php echo $this->baseUrl('/admin/student/department-lesson-pdf-list/'.$lesson->les_id);?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Pdf Öğrenci Listesi                                            
                                                    </a>
                                                    <a class="btn btn-info" href="<?php echo $this->baseUrl('/admin/lesson/edit/'.$lesson->les_id);?>">
                                                            <i class="icon-edit icon-white"></i>  
                                                            Düzenle                                            
                                                    </a>
                                                <?php if($lesson->les_is_deleted == 'false'){ ?>
                                                    <a class="btn btn-danger" href="<?php echo $this->baseUrl().'/admin/lesson/un-publish/' . $lesson->les_id;?>">
                                                            <i class="icon-trash icon-white"></i> 
                                                            Yayından Kaldır
                                                    </a>
                                                <?php } else { ?>
                                                    <a class="btn btn-warning" href="<?php echo $this->baseUrl().'/admin/lesson/publish/' . $lesson->les_id;?>">
                                                            <i class="icon-trash icon-white"></i> 
                                                            Yayınla
                                                    </a>
                                                <?php }  ?>
                                            </td>
                                    </tr>
                                  <?php  }};?>
                                    
                                  <?php 
                                  //Öğretmeni olmayan dersler
                                  if(count($this->lessons_with_no_teacher)){
                                      foreach ($this->lessons_with_no_teacher as $lesson) {
                                  ?>
                                    
                                    <tr>
                                            <td class="center"><?php echo $lesson->les_name ;?></td>
                                            <td class="center"><?php echo ucfirst($lesson->class_name)?></td>
                                            <td class="center">
                                                Öğretmen Atanmadı
                                            </td>
                                            <td class="center">
                                                    <a class="btn btn-success" href="<?php echo $this->baseUrl('/admin/lesson/lesson-students/'.$lesson->les_id);?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Alan Öğrenciler                                            
                                                    </a>
                                                    <a class="btn btn-success" href="<?php echo $this->baseUrl('/admin/student/department-class-pdf-list/'.$lesson->les_id);?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Pdf Öğrenci Listesi                                            
                                                    </a>
                                                    <a class="btn btn-info" href="<?php echo $this->baseUrl('/admin/lesson/edit/'.$lesson->les_id);?>">
                                                            <i class="icon-edit icon-white"></i>  
                                                            Düzenle                                            
                                                    </a>
                                                <?php if($lesson->les_is_deleted == 'false'){ ?>
                                                    <a class="btn btn-danger" href="<?php echo $this->baseUrl().'/admin/lesson/un-publish/' . $lesson->les_id;?>">
                                                            <i class="icon-trash icon-white"></i> 
                                                            Yayından Kaldır
                                                    </a>
                                                <?php } else { ?>
                                                    <a class="btn btn-warning" href="<?php echo $this->baseUrl().'/admin/lesson/publish/' . $lesson->les_id;?>">
                                                            <i class="icon-trash icon-white"></i> 
                                                            Yayınla
                                                    </a>
                                                <?php }  ?>
                                            </td>
                                    </tr>
                                  <?php  }};?>
                              </tbody>
                      </table>            
                    </div>
            </div><!--/span-->

    </div><!--/row-->

    <div class="row-fluid sortable">
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-edit"></i>Ders Ekle</h2>
                              <div class="box-icon">
                                    <a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                <div class="box-content">
                              <fieldset>
                                    <?php echo $this->form;?>
                              </fieldset>

                    </div>
            </div><!--/span-->

</div><!--/row-->
