<div>
				<ul class="breadcrumb">
					<li>
						<a href="#">Anasayfa</a> <span class="divider">/</span>
					</li>
					<li>
                                            <a href="#"><?php echo ucfirst($this->departmentName);?></a><span class="divider">/</span>
					</li>
					<li>
						<a href="#">Dersler</a>
					</li>
				
</div>
    <div class="row-fluid sortable">		
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-user"></i> Öğretim Görevlileri</h2>
                            <div class="box-icon">
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                    <div class="box-content">
                            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                              <thead>
                                      <tr>
                                              <th>Adı</th>
                                              <th>Soyadı</th>
                                              <th></th>
                                      </tr>
                              </thead>   
                              <tbody>
                                  <?php
                                  //Öğretmeni olan dersler
                                  if(count($this->teachers)){
                                      foreach ($this->teachers as $teacher) {
                                  ?>
                                    
                                    <tr>
                                            <td class="center"><?php echo $teacher->name ;?></td>
                                            <td class="center"><?php echo $teacher->surname?></td>
                                            <td class="center">
                                                <a href="<?php echo $this->baseUrl('/admin/teacher/show/'.$teacher->id);?>" class="btn btn-success">Görüntüle</a>
                                            </td>
                                    </tr>
                                  <?php  }};?>
                              </tbody>
                      </table>            
                    </div>
            </div><!--/span-->

    </div><!--/row-->