<html>
    <head>
        
    </head>
    <style>
        body { 
            background: url('/img/pdf_background.jpg');
            background-repeat:no-repeat;
            background-attachment:fixed;
            background-position:center; 
        }
    </style>
    <body>
    
    
        <h1 style='text-align: center'><?php echo $this->department->name." Bölümü"; ?>
        </h1>
        <h3 style='text-align: center'><?php echo $this->class->name; ?>
        </h3>
<br><br>
        <h2>Öğrenci Listesi</h2>
        <br><br>
            <table border="0">
                 <tr>
                    <td style="font-weight:bold">Öğrenci No</td>
                    <td style="font-weight:bold">İsim</td>
                    <td style="font-weight:bold">Soyisim</td>
                </tr>
                    <?php if(count($this->student_ids)){
                        $memberModel = new Application_Model_DbTable_Members();
                        foreach ($this->students as $student) { 
                     ?>
                            <tr>
                                <td><?php echo $student->studentNumber;?></td>
                                <td><?php echo $student->name;?></td>
                                <td><?php echo $student->surname;?></td>
                            </tr>
                    <?php }
                        }; 
                    ?>
            </table>
    </body>
</html>