<div class="span2 main-menu-span">
        <div class="well nav-collapse sidebar-nav">
                <ul class="nav nav-tabs nav-stacked main-menu">
                        <li class="nav-header hidden-tablet">Menu</li>
                        <li><a class="ajax-link" href="<?php echo $this->baseUrl();?>"><i class="icon-home"></i><span class="hidden-tablet">Anasayfa</span></a></li>
                        <li><a class="ajax-link" href="<?php echo $this->baseUrl();?>/teacher/lesson"><i class="icon-eye-open"></i><span class="hidden-tablet">Verdiğim Dersler</span></a></li>
                        <li><a class="ajax-link" href="<?php echo $this->baseUrl();?>/teacher/homework"><i class="icon-edit"></i><span class="hidden-tablet">Verdiğim Ödevler</span></a></li>
                        <li><a class="ajax-link" href="<?php echo $this->baseUrl();?>/teacher/announcement"><i class="icon-edit"></i><span class="hidden-tablet">Yaptığım Duyurular</span></a></li>
                        <li><a class="ajax-link" href="<?php echo $this->baseUrl();?>/teacher/exams/future-exams"><i class="icon-edit"></i><span class="hidden-tablet">Yapılacak Sınavlar</span></a></li>
                        <li><a class="ajax-link" href="<?php echo $this->baseUrl();?>/teacher/student/waiting-lesson-students"><i class="icon-picture"></i><span class="hidden-tablet">Ders Kaydı Onayı Bekleyen Öğrenciler</span></a></li>
                </ul>
            
            
            <!-- Eğer Danışman Hoca İse-->
            <?php if($this->user->is_advisor == "true"){ ?>
                 <ul class="nav nav-tabs nav-stacked main-menu">
                            <li class="nav-header hidden-tablet">Bölüm</li>
                        <li><a class="ajax-link" href="<?php echo $this->baseUrl();?>/teacher/department-students/waiting-students"><i class="icon-list-alt"></i><span class="hidden-tablet">Bölüm Kaydı Onayı Bekleyen Öğrenciler</span></a></li>
                        <li><a class="ajax-link" href="<?php echo $this->baseUrl();?>/teacher/department-lessons"><i class="icon-list-alt"></i><span class="hidden-tablet">Bölüm Dersleri</span></a></li>
                        <li><a class="ajax-link" href="<?php echo $this->baseUrl();?>/teacher/department-exams"><i class="icon-list-alt"></i><span class="hidden-tablet">Bölüm Sınavları</span></a></li>
                </ul>
            <?php } ?>
            <label id="for-is-ajax" class="hidden-tablet" for="is-ajax"><a class="ajax-link" href="<?php echo $this->baseUrl();?>/teacher/index/logout">Çıkış</a></label>
        </div><!--/.well -->
</div><!--/span-->
