<div>
				<ul class="breadcrumb">
					<li>
						<a href="#">Anasayfa</a> <span class="divider">/</span>
					</li>
					<li>
						<a href="#">Öğrenci Listeleri</a>
					</li>
				
</div>
 <?php foreach($this->classList as $class){
                    $studentModel = new Application_Model_DbTable_Members();
                    $students = $studentModel->getAll(array('class_id' => $class->id,'department_id' => $this->department->id));
                ?>
    <div class="row-fluid sortable">		
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-user"></i> <?php echo $class->name;?></h2>
                            <div class="box-icon">
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                
                    <div class="box-content">
                            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                              <thead>
                                      <tr>
                                              <th>Adı</th>
                                              <th>Soyadı</th>
                                              <th>Numarası</th>
                                              <th></th>
                                      </tr>
                              </thead>   
                              <tbody>
                                  <?php if(count($students)){
                                    foreach ($students as $student) { 
                                  ?>
                                    <tr>
                                            <td><?php echo $student->name;?></td>
                                            <td><?php echo $student->surname;?></td>
                                            <td><?php echo $student->studentNumber;?></td>
                                            <td class="center">
                                                    <a class="btn btn-success" href="<?php echo $this->baseUrl().'/admin/student/show/' .$student->id;?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Görüntüle                                            
                                                    </a>
                                            </td>
                                    </tr>
                                  <?php  }};?>
                                    
                              </tbody>
                      </table>            
                    </div>
                <center>
                    <a class="btn btn-large btn-primary" href="<?php echo $this->baseUrl().'/admin/student/department-class-pdf-list/' . $this->department->id."-".$class->id;?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Pdf çıktısı al                                            
                    </a>
                </center><br>
            </div><!--/span-->

    </div><!--/row-->
 <?php } ?>