<div>
				<ul class="breadcrumb">
					<li>
						<a href="#">Anasayfa</a> <span class="divider">/</span>
					</li>
					<li>
						<a href="#">Bölümler</a>
					</li>
				
</div>
    <div class="row-fluid sortable">		
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-user"></i> Bölümler</h2>
                            <div class="box-icon">
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                    <div class="box-content">
                            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                              <thead>
                                      <tr>
                                              <th>Adı</th>
                                              <th>Danışmanı</th>
                                              <th></th>
                                      </tr>
                              </thead>   
                              <tbody>
                                  <?php if(count($this->departments)){
                                    $memberModel = new Application_Model_DbTable_Members();
                                    foreach ($this->departments as $department) { ?>
                                    <tr>
                                    <?php
                                        if( $department->advisor_id != 0) {
                                            $advisor =$memberModel->getByFilter(array('id' => $department->advisor_id))->name;
                                        }
                                        else{
                                            $advisor = "Atanmadı";
                                        }
                                     ?>
                                            <td><?php echo $department->name;?></td>
                                            <td class="center"><?php echo $advisor;?></td>
                                            <td class="center">
                                                    <a class="btn btn-success" href="<?php echo $this->baseUrl().'/admin/student/department-list/' . $department->id;?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Öğrenci Listeleri                                            
                                                    </a>
                                            </td>
                                    </tr>
                                  <?php  }};?>
                              </tbody>
                      </table>            
                    </div>
            </div><!--/span-->

    </div><!--/row-->
