<div class="span2 main-menu-span">
       <div class="well nav-collapse sidebar-nav">
                <ul class="nav nav-tabs nav-stacked main-menu">
                        <li class="nav-header hidden-tablet">Menu</li>
                        <li><a class="ajax-link" href="<?php echo $this->baseUrl("/admin");?>"><i class="icon-home"></i><span class="hidden-tablet"> Anasayfa</span></a></li>
                        <li><a class="ajax-link" href="<?php echo $this->baseUrl();?>/admin/department"><i class="icon-eye-open"></i><span class="hidden-tablet">Bölümler</span></a></li>
                        <li><a class="ajax-link" href="<?php echo $this->baseUrl();?>/admin/class""><i class="icon-edit"></i><span class="hidden-tablet">Sınıflar</span></a></li>
                        <li><a class="ajax-link" href="<?php echo $this->baseUrl();?>/admin/announcement""><i class="icon-edit"></i><span class="hidden-tablet">Duyurular</span></a></li>
                        <li><a class="ajax-link" href="<?php echo $this->baseUrl();?>/admin/index/sitemap"><i class="icon-picture"></i><span class="hidden-tablet">Site Haritası</span></a></li>
                        <li><a class="ajax-link" href="<?php echo $this->baseUrl();?>/admin/index/backupdb"><i class="icon-picture"></i><span class="hidden-tablet">Veri Tabanı Yedegini Al</span></a></li>
                        <label id="for-is-ajax" class="hidden-tablet" for="is-ajax"><a href="<?php echo $this->baseUrl();?>/admin/index/logout">Çıkış</a></label>
        </div><!--/.well -->
</div><!--/span-->
