<!--- datepicker css   -->
<link rel="stylesheet" type="text/css" media="screen" href="/datetimepicker/bootstrap-datetimepicker.min.css">

<form action="/teacher/homework/lesson-homeworks/<?php echo $this->lesson->id;?>" method="post">
    
    <!--- Teacher department class lesson information -->
    <input type="hidden" name="teacher_id" value="<?php echo $this->user->id ?>">
    <input type="hidden" name="lesson_id" value="<?php echo $this->lesson->id ?>">
    <input type="hidden" name="department_id" value="<?php echo $this->lesson->department_id ;?>">
    <input type="hidden" name="class_id" value="<?php echo $this->lesson->class_id ?>">
    <fieldset>
        <label for="title">Başlık</label>
        <input type="text" name="title" id="title" placeHolder="Başlığı giriniz" required>
    </fieldset>
    
    <fieldset>
        <label for="detail">Detay</label>
        <textarea name="detail" class="cleditor" id="detail" placeHolder="Detayı giriniz" required></textarea>
    </fieldset>
   
    <fieldset>
        <label for="finish">Bitiş Zamanı</label>
        <div id="datetimepicker" class="input-append date">
            <input type="text" name="finish_time"></input>
            <span class="add-on">
              <i data-time-icon="icon-time" data-date-icon="icon-calendar" required></i>
            </span>
        </div>
    </fieldset>
    <input type="submit" class="btn btn-primary" value="kaydet">
</form>

<script type="text/javascript"
     src="/datetimepicker/jquery.min.js">
</script> 
<script type="text/javascript"
 src="/datetimepicker/bootstrap.min.js">
</script>
<script type="text/javascript"
 src="/datetimepicker/bootstrap-datetimepicker.min.js">
</script>
<script type="text/javascript"
 src="/datetimepicker/bootstrap-datetimepicker.tr.js">
</script>
<script type="text/javascript">
  $('#datetimepicker').datetimepicker({
    format: 'yyyy/MM/dd hh:mm:ss',
    language: 'tr'
  });
</script>

