<div>
				<ul class="breadcrumb">
					<li>
						<a href="#">Anasayfa</a> <span class="divider">/</span>
					</li>
					<li>
						<a href="#">Sınavlar</a>
					</li>
                                </ul>
				
</div>
    <div class="row-fluid sortable">		
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-user"></i>Sınavlar</h2>
                            <div class="box-icon">
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                    <div class="box-content">
                            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                              <thead>
                                      <tr>
                                              <th>Sınav Başlangıcı</th>
                                              <th>Sınav Bitişi</th>
                                              <th>Bölüm</th>
                                              <th>Sınıf</th>
                                              <th>Ders</th>
                                              <th></th>
                                      </tr>
                              </thead>   
                              <tbody>
                                  <?php if(count($this->exams)){
                                    foreach ($this->exams as $exam) {
                                  ?>


                                    <tr>
                                            <td class="center"><?php echo $exam->exam_start_time ?></td>
                                            <td class="center"><?php echo $exam->exam_finish_time ?></td>
                                            <td class="center"><?php echo $exam->department_name ?></td>
                                            <td class="center"><?php echo $exam->class_name; ?></td>
                                            <td class="center"><?php echo $exam->lesson_name; ?></td>
                                            <td class="center">
                                                
                                                    
                                                    <a class="btn btn-success" href="<?php echo $this->baseUrl('/teacher/exams/show/'.$exam->exam_id);?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Görüntüle                                            
                                                    </a>
                                                    <a class="btn btn-info" href="<?php echo $this->baseUrl('/teacher/exams/edit/'.$exam->exam_id);?>">
                                                            <i class="icon-edit icon-white"></i>  
                                                            Düzenle                                            
                                                    </a>
                                                    <a class="btn btn-danger" href="#">
                                                            <i class="icon-trash icon-white"></i> 
                                                            Sil
                                                    </a>
                                                    
                                                    <a class="btn btn-danger" href="<?php echo $this->baseUrl('/teacher/exams/pdf-download/'.$exam->exam_id);?>">
                                                            <i class="icon-trash icon-white"></i> 
                                                            Pdf İndir
                                                    </a>
                                                         <a class="btn btn-primary" href="<?php echo $this->baseUrl('/teacher/exams/questions/'.$exam->exam_id);?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Sorular                                            
                                                         </a>    
                                            </td>
                                    </tr>
                                  <?php  }};?>
                              </tbody>
                      </table>            
                    </div>
            </div><!--/span-->

    </div><!--/row-->