<div>
				<ul class="breadcrumb">
					<li>
						<a href="#">Anasayfa</a> <span class="divider">/</span>
					</li>
					<li>
						<a href="#">Sınavlar</a>
					</li>
                                </ul>
				
</div>
    <div class="row-fluid sortable">		
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-user"></i>Sınavlar</h2>
                            <div class="box-icon">
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                    <div class="box-content">
                            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                              <thead>
                                      <tr>
                                              <th>Sınav Başlangıcı</th>
                                              <th>Sınav Bitişi</th>
                                              <th>Başlık</th>
                                              <th>Tür</th>
                                              <th></th>
                                      </tr>
                              </thead>   
                              <tbody>
                                  <?php if(count($this->exams)){
                                    foreach ($this->exams as $exam) {
                                  ?>


                                    <tr>
                                            <td class="center"><?php echo $exam->start_time; ?></td>
                                            <td class="center"><?php echo $exam->finish_time; ?></td>
                                            <td class="center"><?php echo $exam->title; ?></td>
                                            <td class="center"><?php echo $exam->type; ?></td>
                                            <td class="center">
                                                
                                                    
                                                    <a class="btn btn-success" href="<?php echo $this->baseUrl('/teacher/exams/show/'.$exam->id);?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Görüntüle                                            
                                                    </a>
                                                    <a class="btn btn-info" href="<?php echo $this->baseUrl('/teacher/exams/edit/'.$exam->id);?>">
                                                            <i class="icon-edit icon-white"></i>  
                                                            Düzenle                                            
                                                    </a>
                                                    <a class="btn btn-danger" href="#">
                                                            <i class="icon-trash icon-white"></i> 
                                                            Sil
                                                    </a>
                                                    
                                                    <a class="btn btn-danger" href="<?php echo $this->baseUrl('/teacher/exams/pdf-download/'.$exam->id);?>">
                                                            <i class="icon-trash icon-white"></i> 
                                                            Pdf İndir
                                                    </a>
                                                    <?php if($exam->type == "online"){ ?>
                                                         <a class="btn btn-primary" href="<?php echo $this->baseUrl('/teacher/exams/questions/'.$exam->id);?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Sorular                                            
                                                         </a>    
                                                    <?php } ?>
                                            </td>
                                    </tr>
                                  <?php  }};?>
                              </tbody>
                      </table>            
                    </div>
            </div><!--/span-->

    </div><!--/row-->

    <div class="row-fluid sortable">
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-edit"></i>Sınav Ekle</h2>
                              <div class="box-icon">
                                    <a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                <div class="box-content">
                              <fieldset>
                                    <?php echo $this->partial('_partial/addexam.phtml', 'teacher', array('lesson' => $this->lesson,'user' => $this->user));?>
                              </fieldset>

                    </div>
            </div><!--/span-->

</div><!--/row-->
