<html>
    <head>
        
    </head>
    <style>
        body { 
            background: url('/img/pdf_background.jpg');
            background-repeat:no-repeat;
            background-attachment:fixed;
            background-position:center; 
        }
    </style>
    <body>
    
         <fieldset>
                                  Başlangıç-Bitiş Tarihi : <?php echo $this->exam->exam_start_time." - ".$this->exam->exam_finish_time; ?> <br>
                                  <h3 style="text-align: center">
                                      <?php echo $this->exam->department_name; ?><br>
                                      <?php echo $this->exam->class_name; ?><br>
                                      <?php echo $this->exam->lesson_name; ?> Dersi <br>
                                      Öğr. Görevlisi : <?php echo $this->exam->teacher_name." ". $this->exam->teacher_surname; ?>  <hr>
                                      <?php echo $this->exam->exam_title; ?>
                                  </h3>
                                  <div>
                                      <?php echo $this->exam->exam_detail;?>
                                  </div>
                              </fieldset>
    <br><br>
<center><h2>Sorular</h2></center>

            <?php if(count($this->questions)){
                $i = 1;
                $choicesModel = new Application_Model_DbTable_Choices();
                foreach ($this->questions as $question) { ?>
                   <div style="font-weight:bold;font-size:14px;color:brown"><?php echo $i."-) ".$question->question; ?></div><br>
                        <?php if($question->type = "multiple choice"){
                            echo "<ul style='list-style-type:lower-alpha'>";
                            foreach ($choicesModel->getAll(array("question_id" => $question->id)) as $choice) {
                                echo "<li style='font-weight:bold;font-size:14'>".$choice->choice."</li><br>";
                            } 
                            echo "</ul>";
                        }?>
             <?php
                $i+=1; 
                    }
                }; 
            ?>
    </body>
</html>