<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js">
</script>

<script>
    function work(){
        if($("#type").val() == "multiple choice"){
                
                $("#choice1-label").show();
                $("#choice2-label").show();
                $("#choice3-label").show();
                $("#choice4-label").show();
                $("#choice5-label").show();;
                $(".choices").show();
            }
            
            if($("#type").val() == "written"){
                $("#choice1-label").hide();
                $("#choice2-label").hide();
                $("#choice3-label").hide();
                $("#choice4-label").hide();
                $("#choice5-label").hide();;
                $(".choices").hide();
            }
    }
    $(document ).ready(function() {
        work();
        $("#type").change(function(){
            work();
        });
    });
         
</script>            
<div>
    <ul class="breadcrumb">
            <li>
                    <a href="#">Anasayfa</a> <span class="divider">/</span>
            </li>
            <li>
                    <a href="#">Sınavlar</a> <span class="divider">/</span>
            </li>
            <li>
                    <a href="#">Sorular</a>
            </li>
    </ul>
</div>
<div class="row-fluid sortable">		
        <div class="box span12">
            <?php if(count($this->questions)){
                $i = 1;
                $choicesModel = new Application_Model_DbTable_Choices();
                foreach ($this->questions as $question) { ?>
                <div class="box-header well" data-original-title>
                        <h2><i class="icon-user"></i><?php echo $i; ?> . Soru</h2>
                        <div class="box-icon">
                                <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                        </div>
                </div>
                <div class="box-content">
                    <div style="font-weight:bold;font-size:17px"><?php echo $question->question; ?></div><br>
                        <?php if($question->type = "multiple choice"){
                            echo "<ul style='list-style-type:lower-alpha'>";
                            foreach ($choicesModel->getAll(array("question_id" => $question->id)) as $choice) {
                                echo "<li>".$choice->choice."</li><br>";
                            } 
                            echo "<br>"
                            . "<center>"
                                    . "<a href='".$this->baseUrl('/teacher/exams/edit-question')."/".$question->id."' class='btn btn-primary'>Duzenle</a>"
                                    . "&nbsp;&nbsp;"
                                    . "<a href='".$this->baseUrl('/teacher/exams/delete-question')."/".$question->id."' class='btn btn-danger'>Sil</a>"
                            . "</center>";
                        }?>
                </div>
            <?php
                $i+=1; 
                    } 
                }; ?>
        </div><!--/span-->

</div><!--/row-->

<div class="row-fluid sortable">
        <div class="box span12">
                <div class="box-header well" data-original-title>
                        <h2><i class="icon-edit"></i>Soru Ekle</h2>
                          <div class="box-icon">
                                <a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
                                <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                        </div>
                </div>
            <div class="box-content">
                          <fieldset>
                                <?php echo $this->form;?>
                          </fieldset>

                </div>
        </div><!--/span-->

</div><!--/row-->
