<div>
				<ul class="breadcrumb">
					<li>
						<a href="#">Anasayfa</a> <span class="divider">/</span>
					</li>
					<li>
						<a href="#">Sınav Detayları</a>
					</li>
                                </ul>
				
</div>
 
<div class="row-fluid sortable">
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-edit"></i>Sınav Detayları</h2>
                              <div class="box-icon">
                                    <a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                <div class="box-content well">
                                    <fieldset>
                                  Başlangıç-Bitiş Tarihi : <?php echo $this->exam->exam_start_time." - ".$this->exam->exam_finish_time; ?> <br>
                                  <h3 style="text-align: center">
                                      <?php echo $this->exam->department_name; ?><br>
                                      <?php echo $this->exam->class_name; ?><br>
                                      <?php echo $this->exam->lesson_name; ?> Dersi <br>
                                      Öğr. Görevlisi : <?php echo $this->exam->teacher_name." ". $this->exam->teacher_surname; ?>  <hr>
                                      <?php echo $this->exam->exam_title; ?>
                                  </h3>
                                  <div class="well">
                                      <?php echo $this->exam->exam_detail;?>
                                  </div><br><br>
                                  <fieldset>
                                      <legend>Sorular</legend>
                                                 <?php if(count($this->questions)){
                                                        $i = 1;
                                                        $choicesModel = new Application_Model_DbTable_Choices();
                                                        foreach ($this->questions as $question) { ?>
                                                           <div style="font-weight:bold;font-size:14px;color:brown"><?php echo $i."-) ".$question->question; ?></div><br>
                                                                <?php if($question->type = "multiple choice"){
                                                                    echo "<ul style='list-style-type:lower-alpha'>";
                                                                    foreach ($choicesModel->getAll(array("question_id" => $question->id)) as $choice) {
                                                                        echo "<li style='font-weight:bold;font-size:14'>".$choice->choice."</li><br>";
                                                                    } 
                                                                    echo "</ul>";
                                                                }?>
                                                     <?php
                                                        $i+=1; 
                                                            }
                                                        }; 
                                                    ?>

                                  </fieldset>
                              </fieldset>
                    </div>
            </div><!--/span-->

</div><!--/row-->