<div>
				<ul class="breadcrumb">
					<li>
						<a href="#">Anasayfa</a> <span class="divider">/</span>
					</li>
					<li>
						<a href="#">Sınıflar</a>
					</li>
				
</div>
    <div class="row-fluid sortable">		
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-user"></i>Sınıflar</h2>
                            <div class="box-icon">
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                    <div class="box-content">
                            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                              <thead>
                                      <tr>
                                              <th>#id#</th>
                                              <th>Sınıf</th
                                              <th></th>
                                              <th></th>
                                      </tr>
                              </thead>   
                              <tbody>
                                  <?php if(count($this->classes)){
                                    foreach ($this->classes as $class) { ?>


                                    <tr>
                                            <td><?php echo $class['id']?></td>
                                            <td class="center"><?php echo $class['name']?></td>
                                            <td class="center">
                                                    <a class="btn btn-info" href="<?php echo $this->baseUrl().'/admin/class/edit/' . $class['id'];?>">
                                                            <i class="icon-edit icon-white"></i>  
                                                            Düzenle                                            
                                                    </a>
                                            </td>
                                    </tr>
                                  <?php  }};?>
                              </tbody>
                      </table>            
                    </div>
            </div><!--/span-->

    </div><!--/row-->

    <div class="row-fluid sortable">
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-edit"></i>Sınıf Ekle</h2>
                              <div class="box-icon">
                                    <a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                <div class="box-content">
                              <fieldset>
                                    <?php echo $this->form;?>
                              </fieldset>

                    </div>
            </div><!--/span-->

</div><!--/row-->
