<!--Footer Starts -->
			<div class="container">
				<div class="footer">
					<div class="row">
						<div class="col-md-12">
							<div class="copy">
                        <!-- This theme comes under Creative Commons Attribution 3.0 Unported. So don't remove below link back. -->
                        <center> Copyright 2013 &copy; <br><a>Hurşit Topal - Alaattin Usta - Ruziye Dağcı</a></center>
							</div>
						</div>
					</div>
				</div>
			</div>
		<!--Footer Ends -->
		
<?php echo $this->headScript()->appendFile($this->baseUrl() . '/staticpages/js/jquery.js'); PHP_EOL?>
<?php echo $this->headScript()->appendFile($this->baseUrl() . '/staticpages/js/bootstrap.min.js'); PHP_EOL?>
<?php echo $this->headScript()->appendFile($this->baseUrl() . '/staticpages/js/respond.min.js'); PHP_EOL?>
<?php echo $this->headScript()->appendFile($this->baseUrl() . '/staticpages/js/html5shiv.js'); PHP_EOL?>
<?php echo $this->headScript()->appendFile($this->baseUrl() . '/staticpages/js/custom.js'); PHP_EOL?>