<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<!--- Select Menu Jquery Kodlamaları --->
<script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
<script>
function work(){
    var department_id = $("#department_id").val();
    var class_id = $("#class_id").val();
    $.getJSON('/teacher/announcement/get-json?department_id='+department_id+"&class_id="+class_id, function(data) {
        var output="";
        for (var i in data) {
            output+="<option value='"+ data[i].id+"'>"+ data[i].name+"</select>";
        }
        document.getElementById("lesson_id").innerHTML=output;
  });
}
$(document).ready(function(){
     work();
     $('#department_id').change(function(){
            work();
     });
     $('#class_id').change(function(){
            work();
     });
});
</script>

<div>
				<ul class="breadcrumb">
					<li>
						<a href="#">Anasayfa</a> <span class="divider">/</span>
					</li>
					<li>
						<a href="#">Duyurular</a>
					</li>
                                </ul>
				
</div>
    <div class="row-fluid sortable">		
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-user"></i> Duyurular</h2>
                            <div class="box-icon">
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                    <div class="box-content">
                            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                              <thead>
                                      <tr>
                                              <th>Bölüm</th>
                                              <th>Sınıf</th>
                                              <th>Ders</th>
                                              <th>Başlık</th>
                                              <th>Gönd. Zamanı</th>
                                              <th></th>
                                      </tr>
                              </thead>   
                              <tbody>
                                  <?php if(count($this->announcements)){
                                    $departmentModel = new Application_Model_DbTable_Department();
                                    $lessonModel = new Application_Model_DbTable_Lesson();
                                    $classModel = new Application_Model_DbTable_Class();
                                    
                                    foreach ($this->announcements as $announcement) {
                                        $lesson = $lessonModel->getByFilter(array('id' => $announcement->class_id))->name;
                                        $class = $classModel->getByFilter(array('id' => $announcement->class_id))->name;
                                        ?>

                                  
                                    <tr>
                                        <td><?php echo $departmentModel->getByFilter(array("id" => $announcement->department_id))->name ?></td>
                                        <td class="center"><?php
                                        if(isset($lesson)) { 
                                            echo $lesson;
                                        }
                                            else{
                                                echo "Hepsi";
                                        }?></td>
                                        
                                        <td class="center"><?php 
                                        if(isset($class)) { 
                                            echo $class ;
                                        }
                                        else{
                                            echo "Hepsi";
                                        }
?></td>
                                            <td class="center"><?php echo substr($announcement->title, 0, 60)?></td>
                                            <td class="center"><?php echo $announcement->time; ?></td>
                                            <td class="center">
                                                    <a class="btn btn-success" href="<?php echo $this->baseUrl('/teacher/announcement/show/'.$announcement->id);?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Görüntüle                                            
                                                    </a>
                                                    <a class="btn btn-info" href="<?php echo $this->baseUrl('/teacher/announcement/edit/'.$announcement->id);?>">
                                                            <i class="icon-edit icon-white"></i>  
                                                            Düzenle                                            
                                                    </a>
                                                    <a class="btn btn-danger" href="#">
                                                            <i class="icon-trash icon-white"></i> 
                                                            Sil
                                                    </a>
                                                    <a class="btn btn-danger" href="<?php echo $this->baseUrl('/teacher/announcement/pdf-download/'.$announcement->id);?>">
                                                            <i class="icon-trash icon-white"></i> 
                                                            Pdf Olarak İndir
                                                    </a>
                                            </td>
                                    </tr>
                                  <?php  }};?>
                              </tbody>
                      </table>            
                    </div>
            </div><!--/span-->

    </div><!--/row-->

    <div class="row-fluid sortable">
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-edit"></i>Duyuru Ekle</h2>
                              <div class="box-icon">
                                    <a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                <div class="box-content">
                              <fieldset>
                                    <?php echo $this->form;?>
                              </fieldset>

                    </div>
            </div><!--/span-->

</div><!--/row-->
