<div>
				<ul class="breadcrumb">
					<li>
						<a href="#">Anasayfa</a> <span class="divider">/</span>
					</li>
					<li>
						<a href="#">Duyuru Detayları</a>
					</li>
                                </ul>
				
</div>
 
<div class="row-fluid sortable">
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-edit"></i>Duyuru Detayları</h2>
                              <div class="box-icon">
                                    <a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                <div class="box-content">
                              <fieldset style='text-align: center' class="well">
                                  <h1>
            <?php $departmentModel = new Application_Model_DbTable_Department();
                echo $departmentModel->getByFilter(array('id' =>  $this->announcement->department_id))->name ;
                echo "<br>";
                if($this->announcement->class_id){
                    $classModel = new Application_Model_DbTable_Class();
                    echo $classModel->getByFilter(array('id' =>  $this->announcement->class_id))->name ;
                    echo "<br>";
                }
                if($this->announcement->lesson_id){
                    $lessonModel = new Application_Model_DbTable_Lesson();
                    echo $lessonModel->getByFilter(array('id' =>  $this->announcement->lesson_id))->name ;
                    echo " Dersi <br><br></h1>";
                }
                echo "<h2>".$this->announcement->title."</h2><br>"; ?>
                              </fieldset>
                    <fieldset class="well">
                        <?php echo $this->announcement->detail;?>
                        <hr>
                        <?php echo $this->announcement->time;?>
                        
                    </fieldset>

                    </div>
            </div><!--/span-->

</div><!--/row-->