<div>
				<ul class="breadcrumb">
					<li>
						<a href="#">Anasayfa</a> <span class="divider">/</span>
					</li>
					<li>
						<a href="#">Ders Bilgileri Güncelleme</a>
					</li>
				
</div>
 <div class="row-fluid sortable">		
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-user"></i> Bilgiler</h2>
                            <div class="box-icon">
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                 <div class="box-content">
                <?php echo $this->form; ?>         
                </div>
        </div><!--/span-->

</div><!--/row-->