<div>
				<ul class="breadcrumb">
					<li>
						<a href="#">Anasayfa</a> <span class="divider">/</span>
					</li>
					<li>
						<a href="#">Öğretim Görevlileri</a>
					</li>
				
</div>
    <div class="row-fluid sortable">		
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-user"></i> Bölümler</h2>
                            <div class="box-icon">
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                    <div class="box-content">
                            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                              <thead>
                                      <tr>
                                              <th>#id#</th>
                                              <th>İsim Soyisim</th>
                                              <th>Email</th>
                                              <th>Telefon</th>
                                              <th>Bölüm</th>
                                              <th></th>
                                      </tr>
                              </thead>   
                              <tbody>
                                  <?php if(count($this->teachers)){
                                    $departmentModel = new Application_Model_DbTable_Department();
                                    foreach ($this->teachers as $teacher) { ?>
                                    
                                    <?php if($teacher->department_id != 0){
                                              $class = $departmentModel->getByFilter(array('id' => $teacher->department_id));
                                          }else{    $class = array('name' => "---");}
                                    ;?>
                                    <tr>
                                            <td><?php echo $teacher->id; ?></td>
                                            <td class="center"><?php echo ucfirst($teacher->name) . " " . strtoupper($teacher->surname) ?></td>
                                            <td class="center"><?php echo $teacher->email;?></td>
                                            <td class="center"><?php echo $teacher->telephone;?></td>
                                            <td class="center"><?php echo $class->name;?></td>
                                            <td class="center">
                                                    <a data-toggle="modal" data-target="#myModal-<?php echo $teacher->id ;?>" class="btn btn-success" href="#">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Görüntüle
                                            
                                                    </a>
                                                    <a class="btn btn-info" href="<?php echo $this->baseUrl().'/admin/teacher/edit/' . $teacher->id;?>">
                                                            <i class="icon-edit icon-white"></i>  
                                                            Düzenle                                            
                                                    </a>
                                                <?php if($teacher['is_deleted'] == 'false'){ ?>
                                                    <a class="btn btn-danger" href="<?php echo $this->baseUrl().'/admin/teacher/un-publish/' . $teacher['id'];?>">
                                                            <i class="icon-trash icon-white"></i> 
                                                            Yetkisizlendir
                                                    </a>
                                                <?php } else { ?>
                                                    <a class="btn btn-warning" href="<?php echo $this->baseUrl().'/admin/teacher/publish/' . $teacher['id'];?>">
                                                            <i class="icon-trash icon-white"></i> 
                                                            Yetkilendir
                                                    </a>
                                                <?php }  ?>
                                            </td>
                                    </tr>
                                  <?php  }};?>
                              </tbody>
                      </table>            
                    </div>
            </div><!--/span-->

    </div><!--/row-->

    <div class="row-fluid sortable">
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-edit"></i>Bölüm Ekle</h2>
                              <div class="box-icon">
                                    <a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                <div class="box-content">
                              <fieldset>
                                    <?php echo $this->form;?>
                              </fieldset>

                    </div>
            </div><!--/span-->

</div><!--/row-->

<?php 
$memberModel = new Application_Model_DbTable_Members();
foreach ($this->teachers as $teacher) { ?>
                                    
<!-- Modal -->
<div class="modal fade" id="myModal-<?php echo $teacher['id'];?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel"><?php echo ucfirst($teacher['name']) . " " . strtoupper($teacher['surname'])?></h4>
      </div>
      <div class="modal-body">
          Email : <?php echo $teacher['email'];?><br>
        Telefon : <?php echo $teacher['telephone'];?><br>
        Verdiği Dersler : Matematik, Fizik, Biyoloji<br>
        Öğrenci Sayısı : 55<br>
        
      </div>
      <div class="modal-footer">
        <a href="<?php echo $this->baseUrl().'/admin/teacher/show/' . $teacher['id'];?>" class="btn btn-default">Detaylı Gör</a>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<?php } ?>