<div>
				<ul class="breadcrumb">
					<li>
						<a href="#">Anasayfa</a> <span class="divider">/</span>
					</li>
					<li>
                                            <a href="#"><?php echo ucfirst($this->departmentName);?></a><span class="divider">/</span>
					</li>
					<li>
						<a href="#">Dersler</a>
					</li>
				
</div>
    <div class="row-fluid sortable">		
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-user"></i> Dersler</h2>
                            <div class="box-icon">
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                    <div class="box-content">
                            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                              <thead>
                                      <tr>
                                              <th>Adı</th>
                                              <th>Sınıfı</th>
                                              <th>Öğretim Görevlisi</th>
                                              <th></th>
                                      </tr>
                              </thead>   
                              <tbody>
                                  <?php if(count($this->lessons)){
                                      $memberModel = new Application_Model_DbTable_Members();
                                      $classModel = new Application_Model_DbTable_Class();
                                      foreach ($this->lessons as $lesson) {
                                            $member = $memberModel->getByFilter(array('id' => $lesson->teacher_id));
                                            $class = $classModel->getByFilter(array('id' => $lesson->class_id));
                                       ?>
                                    
                                    <tr>
                                            <td class="center"><?php echo $lesson->name;?></td>
                                            <td class="center"><?php echo ucfirst($class->name);?></td>
                                            <td class="center">
                                            <?php 
                                                if(count($member)){
                                                    echo ucfirst($member->name) . " " . strtoupper($member['surname']);
                                                }
                                                else{
                                                    echo "Öğretmen Ataması Yapılmadı";
                                                }
                                            ?>
                                            
                                            
                                            </td>
                                            <td class="center">
                                                    <a class="btn btn-success" href="<?php echo $this->baseUrl('/advisor/lesson/lesson-students/'.$lesson['id']);?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Alan Öğrenciler                                            
                                                    </a>
                                                    <a class="btn btn-info" href="<?php echo $this->baseUrl('/advisor/department-lessons/edit/'.$lesson['id']);?>">
                                                            <i class="icon-edit icon-white"></i>  
                                                            Düzenle                                            
                                                    </a>
                                                <?php if($lesson['is_deleted'] == 'false'){ ?>
                                                    <a class="btn btn-danger" href="<?php echo $this->baseUrl().'/advisor/department-lessons/un-publish/' . $lesson['id'];?>">
                                                            <i class="icon-trash icon-white"></i> 
                                                            Yayından Kaldır
                                                    </a>
                                                <?php } else { ?>
                                                    <a class="btn btn-warning" href="<?php echo $this->baseUrl().'advisor/department-lessons/publish/' . $lesson['id'];?>">
                                                            <i class="icon-trash icon-white"></i> 
                                                            Yayınla
                                                    </a>
                                                <?php }  ?>
                                            </td>
                                    </tr>
                                  <?php  }};?>
                              </tbody>
                      </table>            
                    </div>
            </div><!--/span-->

    </div><!--/row-->

    <div class="row-fluid sortable">
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-edit"></i>Ders Ekle</h2>
                              <div class="box-icon">
                                    <a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                <div class="box-content">
                              <fieldset>
                                    <?php echo $this->form;?>
                              </fieldset>

                    </div>
            </div><!--/span-->

</div><!--/row-->
