<div>
				<ul class="breadcrumb">
					<li>
						<a href="#">Ödevler</a>
					</li>
                                </ul>
				
</div>
    <div class="row-fluid sortable">		
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-user"></i> Ödevler</h2>
                            <div class="box-icon">
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                    <div class="box-content">
                            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                              <thead>
                                      <tr>
                                              <th>Ders</th>
                                              <th>Başlık</th>
                                              <th>Öğretim Görevlisi</th>
                                              <th>Bitiş Zamanı</th>
                                              <th></th>
                                      </tr>
                              </thead>   
                              <tbody>
                                    <?php if(count($this->homeworks)){
                                              foreach ($this->homeworks as $homework) {
                                    ?>
                                    <tr>
                                        <td><?php echo $homework->lesson_name; ?></td>
                                            <td><?php echo $homework->hw_title ;?></td>
                                            <td class="center"><?php echo $homework->teacher_name." ".$homework->teacher_surname  ?></td>
                                            <td><?php echo $homework->hw_finish_time ;?></td>
                                            <td class="center">
                                                    <a class="btn btn-success" href="<?php echo $this->baseUrl('/student/homework/show/'.$homework->hw_id);?>">
                                                            <i class="icon-zoom-in icon-white"></i>  
                                                            Görüntüle                                            
                                                    </a>
                                            </td>
                                    </tr>
                                  <?php   }};?>
                              </tbody>
                      </table>            
                    </div>
            </div><!--/span-->

    </div><!--/row-->