<div>
				<ul class="breadcrumb">
					<li>
						<a href="#">Anasayfa</a> <span class="divider">/</span>
					</li>
					<li>
						<a href="#">Ödev Detayları</a>
					</li>
                                </ul>
				
</div>
 
<div class="row-fluid sortable">
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-edit"></i>Ödev Detayları</h2>
                              <div class="box-icon">
                                    <a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                <div class="box-content">
                              <fieldset class="well">
                                  Bitiş : <?php echo $this->homework->hw_finish_time; ?> <br>
                                  <h2 style="text-align: center"><?php echo $this->homework->department_name; ?> </h2>
                                  <h2 style="text-align: center"><?php echo $this->homework->class_name; ?> </h2>
                                  <h2 style="text-align: center"><?php echo $this->homework->lesson_name; ?> Dersi </h2>
                                  <h2 style="text-align: center"><?php echo $this->homework->hw_title; ?></h2>
                                  <div class="well"><?php echo $this->homework->hw_title; ?> </div>
                              </fieldset>

                    </div>
            </div><!--/span-->

</div><!--/row-->

<?php 
    if($this->homework_status && !$this->status){                         
?>
<div class="row-fluid sortable">
            <div class="box span12">
                    <div class="box-header well" data-original-title>
                            <h2><i class="icon-edit"></i>Ödev Gönder</h2>
                              <div class="box-icon">
                                    <a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
                                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                            </div>
                    </div>
                <div class="box-content">
                              <fieldset>
                                    <?php echo $this->form; ?>
                              </fieldset>

                    </div>
            </div><!--/span-->

</div><!--/row-->
<?php } ?>

<?php 
if($this->status){ 
?>        
<div class="alert alert-success">Ödevi Gönderdiniz</div>
<?php } ?>                         

    
    
    
<?php 
if(!$this->homework_status){      
?>
<div class="alert alert-danger">Ödevin Zamanı Geçti</div>
<?php } 

